# Generated by Django 5.2.7 on 2025-11-06 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('IMP', 'Importación (EE. UU. a El Salvador)'), ('EXP', 'Exportación (El Salvador a EE. UU.)')], max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('PROC', 'En Proceso'), ('COMP', 'Completada')], default='PEND', max_length=5)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ej: Ropa, Electrónica, Documentos', max_length=255)),
                ('peso_lb', models.DecimalField(decimal_places=2, max_digits=6)),
                ('largo_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ancho_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alto_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_declarado_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizaciones.cotizacion')),
            ],
        ),
    ]
