# Generated by Django 5.2.8 on 2025-11-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('IMP', 'Importación (EE. UU. a El Salvador)'), ('EXP', 'Exportación (El Salvador a EE. UU.)')], max_length=3, unique=True)),
                ('precio_libra', models.DecimalField(decimal_places=2, help_text='Costo por libra en USD', max_digits=5)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
